"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import dj_database_url
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", cast=bool, default=False)

ALLOWED_HOSTS = config(
    "DJANGO_ALLOWED_HOSTS",
    default=".onrender.com,emptymyinbox.app",
    cast=Csv(),
)

# CSRF trusted origins - required for cross-origin requests
_raw_csrf_trusted_origins = config(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default="https://*.onrender.com,https://emptymyinbox.app",
    cast=Csv(),
)
CSRF_TRUSTED_ORIGINS = [origin.rstrip("/") for origin in _raw_csrf_trusted_origins]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "emails",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = config("DATABASE_URL", default=None)
SUPABASE_DIRECT_CONNECT = config("SUPABASE_DIRECT_CONNECT", default=None)
DB_CONN_MAX_AGE = config("DB_CONN_MAX_AGE", cast=int, default=600)

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=DB_CONN_MAX_AGE,
            ssl_require=True,
        )
    }
elif SUPABASE_DIRECT_CONNECT:
    DATABASES = {
        "default": dj_database_url.parse(
            SUPABASE_DIRECT_CONNECT,
            conn_max_age=DB_CONN_MAX_AGE,
            ssl_require=True,
        )
    }
else:
    raise ValueError("DATABASE_URL or SUPABASE_DIRECT_CONNECT must be set.")

default_db = DATABASES["default"]
default_db.setdefault("OPTIONS", {})
default_db["OPTIONS"].setdefault("sslmode", "require")

host = default_db.get("HOST") or ""
if "pooler.supabase.com" in host:
    default_db["OPTIONS"]["prepare_threshold"] = 0


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # SessionAuthentication removed - we use JWT tokens in Authorization headers
        # JWT tokens are NOT vulnerable to CSRF (browsers don't auto-send custom headers)
        # SessionAuthentication would require CSRF protection, but we don't need it
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

# JWT Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# CORS settings
_raw_cors_allowed_origins = config(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    default="https://*.onrender.com,https://emptymyinbox.app",
    cast=Csv(),
)
CORS_ALLOWED_ORIGINS = [origin.rstrip("/") for origin in _raw_cors_allowed_origins]

CORS_ALLOW_CREDENTIALS = True

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = config(
    "DJANGO_SECURE_SSL_REDIRECT",
    cast=bool,
    default=not DEBUG,
)

# Gmail API settings
GMAIL_CLIENT_ID = config("GMAIL_CLIENT_ID")
GMAIL_CLIENT_SECRET = config("GMAIL_CLIENT_SECRET")
GMAIL_REDIRECT_URI = config("GMAIL_REDIRECT_URI")
FRONTEND_SUCCESS_URL = config("FRONTEND_SUCCESS_URL")

# Celery Configuration (for background tasks)
CELERY_BROKER_URL = config(
    "CELERY_BROKER_URL",
    default="redis://redis:6379/0",
)
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND",
    default=CELERY_BROKER_URL,
)
