# Generated by Django 4.2 on 2025-11-06 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name="emailaccount",
            unique_together={("user", "email")},
        ),
    ]
