# Generated by Django 4.2 on 2025-11-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0002_alter_emailaccount_email_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="email",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="emailaccount",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="email",
            index=models.Index(
                fields=["account", "is_read"], name="emails_emai_account_cd8354_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="email",
            index=models.Index(
                fields=["account", "received_at"], name="emails_emai_account_faa3b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailaccount",
            index=models.Index(
                fields=["user", "is_active"], name="emails_emai_user_id_7aeed9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="email",
            constraint=models.UniqueConstraint(
                fields=("account", "gmail_id"), name="unique_account_gmail_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailaccount",
            constraint=models.UniqueConstraint(
                fields=("user", "email"), name="unique_user_email"
            ),
        ),
    ]
