# Generated by Django 4.2 on 2025-11-09 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0004_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gmail_filter_id", models.CharField(db_index=True, max_length=255)),
                ("criteria", models.JSONField(default=dict)),
                ("actions", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filters",
                        to="emails.emailaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="filter",
            index=models.Index(
                fields=["account"], name="emails_filt_account_fcfdc9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="filter",
            constraint=models.UniqueConstraint(
                fields=("account", "gmail_filter_id"), name="unique_account_filter_id"
            ),
        ),
    ]
