# Generated by Django 4.2 on 2025-11-15 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emails", "0005_filter_filter_emails_filt_account_fcfdc9_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GmailOAuthState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255, unique=True)),
                ("redirect_uri", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gmail_oauth_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="gmailoauthstate",
            index=models.Index(fields=["state"], name="emails_gmai_state_923b9b_idx"),
        ),
    ]
